language: go

go:
        - 1.7.x
        - 1.8.x
        - master

install:
        - go get github.com/shenwei356/bio
        - go get github.com/spf13/cobra
        - go get github.com/spf13/viper
